language: node_js
node_js:
  - "0.10"
after_script:
  - npm run coveralls
before_script:
  - openssl aes-256-cbc -k "$secret" -in config.coffee.enc -d -a -out config.coffee
env:
  global:
    - secure: "Fpr92oNY70FgxAX0a/FOSUGnfcPYJAzDQjtDRhcFrlprgYS96rXkJ5BfrIAwTNP0AeaFmBIOhfKysjMi/L7q8V+D/CDh5umrS9zXQquckgwfZtfZXF1QIG16IXyS1YZxbmjyw5Kb95jPZOznb8bBJLuI83eFSrBDYlYtl5c+B3c="
