language: node_js
node_js:
  - "0.10"
after_script:
  - npm run coveralls
before_script:
  - openssl aes-256-cbc -k "$secret" -in config.coffee.enc -d -a -out config.coffee
env:
  global:
    - secure: "DPYz7qDCECGDAaVk66gQ+seZ58DNU2PGPkoaaIz9LCHlHlUMV0Xpen+eS2k42SMfR2PjIWr/PyillfPJ4UkudMcIa5ubGSS8zjFBJfiek5RMNrklEO3IK1WZTwUL64UzmTQVQ5bNbsZEUopcKCYF8/APem4+5zifEk8TOYwSLSM="
