language: node_js
node_js:
  - "0.10"
after_script:
  - npm run coveralls
before_script:
  - openssl aes-256-cbc -k "$secret" -in config.coffee.enc -d -a -out config.coffee
env:
  global:
    - secure: "g90Sdc3qsrjQTUoYs5YC+R+/uaPhrZ2I3SuZBgDDaLziwS0i+vLzqPubPRyKrI/kRs0iI2o4rIwKKixnlWE42tIS4meSR0maNNvjlqrcSYMQGkjrReHt5/MCRl4lAW/5EW4jhv/Kw2jpBeJjkyQEH1WVmF4rc+ZBFVo5ww2qpVk="
