language: node_js
node_js:
  - 0.1
after_script:
  - npm run coveralls
before_script:
  - openssl aes-256-cbc -k "$secret" -in config.coffee.enc -d -a -out config.coffee
env:
  global:
    - secure: LMvofun1QvizQ/DgDP7YCZbv3bGZuvq5418726zmBsUk+2x1Zpymse8Sw/m4vtYdzl2ao+pmmxCweXoB1IfhzbwHwKqAHxL6bMxsJD4/7NabNu3Wy6/MTwr6LGNGhWkty5kSvmBRIXYw0hkBz7iT412vJFMv6Mwohg8oRq1YEjY=
